# This is a basic workflow to help you get started with Actions

name: Launch

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  [workflow_dispatch]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  config-env:
    # The type of runner that the job will run on
    runs-on: ubuntu-20.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: update apt
        run: sudo apt update
  
      - name: install build essential
        run: sudo apt install build-essential
      
      - name: add apt gobjc gfortran gnat
        run: sudo apt install gobjc gfortran gnat
        
      - name: verify installs
        run: |
              gcc --version
              g++ --version
      
      - name: Checkout
        uses: actions/checkout@v3


      - name: Experiment
        run: |
          pwd                    
          cd public
          ls
          pwd 
          sudo apt install -y ./argos3_simulator-3.0.0-x86_64-beta59.deb

      # - name: check download of argos3         
      #   run:  ls  

      # - name: donwload argos3
      #   uses: suisei-cn/actions-download-file@v1.3.0
      #   id: downloadfile  # Remember to give an ID if you need the output filename
      #   with:
      #      url: "https://drive.google.com/u/0/uc?id=1oO2lb2LuLq4IrZmNMiJurWTotHp_pDye&export=download&confirm=t&uuid=765c3a2c-9b95-47b0-9f62-2f614eba47c8&at=AHV7M3c7OYhDwKDBog2PiTvYw5Kz:1668440077169"
      #      target: ./home/runner/work/irs-q-learning-project/irs-q-learning-project/public/

      # - name: go to download
      #   run: cd ./home/runner/work/irs-q-learning-project/irs-q-learning-project/public/
        
      # - name: check download of argos3         
      #   run:  ls   

      # - name: install argos3         
      #   run:  sudo apt install -y ./home/runner/work/irs-q-learning-project/irs-q-learning-project/public/argos3_simulator-3.0.0-x86_64-beta59.deb

      - name: verify installation
        run: argos3 --v
      
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      #- uses: actions/checkout@v3
