# This is a basic workflow to help you get started with Actions

name: Launch

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  [workflow_dispatch]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  run-simulator:
    # The type of runner that the job will run on
    runs-on: ubuntu-20.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: update apt
        run: sudo apt update
  
      - name: install build essential
        run: sudo apt install build-essential
      
      - name: add apt gobjc gfortran gnat
        run: sudo apt install gobjc gfortran gnat
        
      - name: verify installs
        run: |
              gcc --version
              g++ --version

      - name: install others
        run: sudo apt-get install cmake libfreeimage-dev libfreeimageplus-dev \
             qt5-default freeglut3-dev libxi-dev libxmu-dev liblua5.3-dev \
             doxygen graphviz libgraphviz-dev asciidoc
      
      - name: Checkout
        uses: actions/checkout@v3

      - name: install argos 3 simulator
        run: |
          cd argos3
          sudo apt install -y ./argos3_simulator-3.0.0-x86_64-beta59.deb

      - name: verify installation
        run: argos3 --version
      
      - name: run simulator
        run: argos3 -c ./circuit-testing.argos
  
  

